name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: NPM Install
        run: npm install
      - name: Create Dummy Password file
        run: echo "module.exports.password = 'DUMMY';" > password.js
      - name: Run Linter
        run: npm run lint
